pub mod analytics;
pub mod backup_scheduler;
pub mod database;
pub mod dbus_service;
#[cfg(target_os = "linux")]
pub mod dbus_watchdog;
pub mod menubar;
pub mod metrics;
pub mod search;
pub mod settings;
pub mod shortcuts;
pub mod tags;
pub mod theme;
pub mod window;
